MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
WPM_ENABLE = yes

OLED_ENABLE = yes
OLED_DRIVER = SSD1306

RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812

LTO_ENABLE = yes
AVR_USE_MINIMAL_PRINTF = yes
SLEEP_LED_ENABLE = no
COMBO_ENABLE = no
AUDIO_ENABLE = no
MIDI_ENABLE = no
BLUETOOTH_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
BOOTMAGIC_ENABLE = no
MAGIC_ENABLE = no
MUSIC_ENABLE = no
NKRO_ENABLE = no






